### ISSUE TITLE
To-do list until next group meeting 

### ISSUE THREAD

**Issue by emilyzhou112** [emilyzhou112/CAGIS-UCGIS-2024#9]
For Junyi: 

- [x] Create a new and pretty workflow in Illustrator 
- [x] Set up a template for our slides 
- [x] Try to draw a fishnet map. 

For Emily:

- [x] Aggregate power usage data into the fishnet
- [x] Redo all WSM, TOPSIS, and PROMETHEE calcualtion
- [x] Figure our the AHP method
- [x] Compare the results across all the methods
- [x] Clean up all the code
- [x] Prepare csv and geojson for plot
